import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import Header from "@/app/(dashboard)/_components/Header";
import dynamic from "next/dynamic";
import { QueryClient, QueryClientProvider } from "react-query";
import { ReactQueryClientProvider } from "@/app/_components/ReactQueryClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const HeaderSSR = dynamic(() => import("./_components/Header"), {
//   ssr: false,
//   loading: () => (
//     <div className={"flex justify-center"}>
//       <span className="loading loading-ring loading-md"></span>
//     </div>
//   ),
// });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="ru">
        <body
          className={`${inter.className} px-4 max-h-[100vh] overflow-hidden`}
        >
          <main className={"grid h-[80vh] pt-4"}>{children}</main>
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
