import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import { ButtonExit } from "@/app/_components/ButtonExit";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = cookies().has("token");
  return (
    <html lang="ru">
      <body className={inter.className}>
        <header>
          <div className={"flex justify-end"}>{token && <ButtonExit />}</div>
        </header>
        {children}
      </body>
    </html>
  );
}
